-- Adds the 10 real SafariBookings.com reviews (copied verbatim from
-- https://www.safaribookings.com/reviews/p6419) into the testimonials table.
-- Safe to run on production: only inserts, no schema changes.
-- Run this in phpMyAdmin (SQL tab) on the live database.

INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Valerie Rodríguez', 'Costa Rica', 5, 'We had an amazing experience with Jambo Masai Tours. From the beginning, communication was excellent, and everything was very well organized. The team was professional, friendly, reliable, and always willing to help. Our safari was truly unforgettable, and our guide was knowledgeable and made the experience even more special. We felt well taken care of throughout the entire trip. Excellent service and great value for money. I highly recommend Jambo Masai Tours to anyone looking for an incredible safari experience in Tanzania!', NULL, 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Wadir', 'United Kingdom', 4, 'We had a really good experience with Jambo Masai Tours overall. Communication was good throughout, and our guide, Shaban, was great. He listened to what we wanted to see and made a real effort to tailor the safari around that.', 'Honeymoon Safari', 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Dianna', 'Netherlands', 5, 'Everything was taken care of! Driver was very enthousiastic and we saw loads of animals. Everything went smoothly and on time. Great value for your money!', NULL, 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Antonella', 'Italy', 5, 'We went on a 7-day shared safari (and Materuni waterfall) with Jambo Masai Tour, and it was fantastic! Everything went perfectly; our guide Enock explained so much about the animals and helped us get to know the parks we visited much better. We even witnessed the Great Migration—a truly unique spectacle. Thanks also to Juliette; she was incredibly kind and helpful, and communication was clear. Asante!', '7-Day Shared Safari & Materuni Waterfall', 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Giulia', 'Italy', 5, 'I came across Jambo Masai Tour after a long search for safari agencies in Tanzania, and I was immediately impressed by the kindness and promptness of the staff, Raphael in particular. We decided to go on safari in Tarangire National Park and Ngorongoro Crater, spending two days travelling from Zanzibar, with all transfers included in the price.', 'Tarangire & Ngorongoro Crater Safari', 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Mon', 'Singapore', 4, 'I booked a tour with Jambo Masai Tours, who outsourced the Kenya portion of my trip to Shades of Africa. My complaint is regarding the services delivered by their outsourced partner.', 'Kenya & Tanzania Multi-Country Safari', 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Taras N', 'United States', 5, 'Our experience with Jambo Masai Tours began in October 2025, when I started planning what I hoped would be the ultimate African safari for my family. I submitted our plans through SafariBookings.com and received several proposals from different operators. Our itinerary was ambitious and logistically complicated: seven days starting in Nairobi, continuing through Amboseli National Park, crossing into Tanzania through Arusha, then Tarangire National Park, Ngorongoro Crater, Central Serengeti, Northern Serengeti, and finally back to Central Serengeti for our departure from Seronera Airstrip to continue our vacation in Zanzibar. From my first conversations with Raphael at Jambo Masai Tours, I was impressed by his responsiveness, flexibility, and willingness to work with us. Raphael managed to put together this complicated Kenya–Tanzania itinerary at a very competitive and family-friendly price while maintaining the quality of accommodations and experiences we wanted.', '7-Day Kenya & Tanzania Family Safari', 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Emily', 'United Kingdom', 3, 'Firstly I had an amazing time on safari, the food and accommodation was great along with the activities we did. However the organisation of the tour was poor. There was multiple times where we were an hour late leaving. When paying to be on safari, personally I want to leave on time to spend the most time in the national parks as possible. The communication was also poor, I had to ask to know what was going on and wasn''t informed unless I asked. My itinerary changed many times so I couldn''t follow it. I cannot fault the people, they were all so lovely and friendly (especially Julieth). However, due to the efficiency and communication I would not use this company again.', NULL, 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Swagata', 'Australia', 5, 'I did the 4 day Serengeti, Ngorongoro and Tarangire safari with Jambo Massai. They were extremely polite, responsive and cooperative from the very beginning when I was looking at options and planning my trip. They had the most competitive quote for lodge stays and service was equally great. The safari guide Lawrence was very polite and knowledgeable. The car driver GodBless, the travel organiser Julieth and the tour manager Rafael were all a delight to talk to. They went over and beyond to make me a solo traveller feel comfortable and happy. I''d definitely recommend JamboMassai tour operator to everyone.', '4-Day Serengeti, Ngorongoro & Tarangire Safari', 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
INSERT INTO testimonials (customer_name, country, rating, review, tour_name, source, source_url, approved) VALUES ('Alice B', 'United States', 5, 'The service provided by Jambo Masai Tours were excellent. They were a value for the money and their services exceeded my expectations. The accommodations were very nice and the driver was always on time and very informative. We were guided every step of the way. Communications were excellent and we were informed of everything that was to take place. We received royal treatment. I will definitely use them again and advise my friends to do the same.', NULL, 'safaribookings', 'https://www.safaribookings.com/reviews/p6419', 1);
